### ISSUE TITLE
Eigenmath g3a

### ISSUE THREAD

**Issue by gbl08ma** [parrotgeek1/CASIO-CG#1]
While I state in the readme of my Eigenmath port that distributing the readme along with the g3a is not mandatory, doing so is recommended, in order to preserve important information about the add-in operation and licensing. This is especially true when archiving add-ins for posterity, as appears to be the case here.

Please replace the Eigenmath g3a with the ZIP you can obtain here: https://tny.im/prEigenZipDL

**Comment by parrotgeek1** [comment]
Fixed, thanks. I did it for some other programs too.
