### ISSUE TITLE
Use Submodules

### ISSUE THREAD

**Issue by ComputerNerd** [parrotgeek1/CASIO-CG#2]
What happens if the author updates their software? Would you really like to feel obligated to update your repository every-time that happens or would you like the easy way?

https://git-scm.com/docs/git-submodule

**Comment by parrotgeek1** [comment]
But if the author deletes their repository does a sub module keep working? Or does it go away?

**Comment by ComputerNerd** [comment]
That is a good point that I did not think of. I think it would go away.
